

class QuSbConstants:
    SYSEX_HEADER = b'\x00\x00\x1A\x50\x11\x01\x00'
    SYSEX_ALL_CALL = b'\x7F'
    SYSEX_GET_SYSTEM_STATE = b'\x10'

    SYSEX_REQUEST_STATE = SYSEX_HEADER + SYSEX_ALL_CALL + SYSEX_GET_SYSTEM_STATE + b'\x00'  # we are not an iPad
    SYSEX_REQUEST_STATE_END = SYSEX_HEADER + b'\x00' + b'\x14'
